Fixed Spinner Color (Dolphin)
AniLeo/Kuroi pull request #1
Opened 2020-04-16 03:35 UTC by MrMendelli

Changed background-color for spinners, spinners previously appear
Fix found by BParks21.

2020-04-16 07:23 UTC, AniLeo commented
This fix is incorrect, there's a reason why every QWidget is transparent by default and specific objects are then painted individually

2020-04-16 07:24 UTC, AniLeo requested changes
Needs painting the specific object, not global QWidget

2020-04-16 10:12 UTC, MrMendelli commented
I didn't realize, my mistake. I was under the impression this was correct as it seemed to work as intended. I will adjust my PR tomorrow.

2020-04-17 08:04 UTC, AniLeo commented
You didn't change anything, perhaps you pushed the wrong commit?

2020-04-21 23:38 UTC, MrMendelli commented
> 
> 
> You didn't change anything, perhaps you pushed the wrong commit?

Let me check, it should be the proper commit.

2020-06-21 06:04 UTC, closed without merging